apiVersion: v1
description: A Helm chart for Kubernetes
name: "drupal-fpm"
version: 0.1.0
keywords:
- drupal-fpm
sources:
- "https://supernami.github.io/helm-charts/"
- "https://hub.docker.com/_/drupal/"
maintainers:
- name: SuperNami
  email: supernami@tutamail.com
