apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ default "default" .Values.namespace }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: "{{ .Values.service.type }}"
  ports:
  - name: http
    protocol: TCP
    port: {{ default 80 .Values.service.httpexternalPort }}
    targetPort: http
  - name: https
    protocol: TCP
    port: {{ default 443 .Values.service.httpsexternalPort }}
    targetPort: https
  selector:
    app: {{ template "fullname" . }}
